version: "3"
services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # Web UI
      - "9000:9000"  # HDFS RPC
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HDFS_NAMENODE_RPC_ADDRESS=0.0.0.0:9000
      - HADOOP_CONF_DIR=/etc/hadoop
    volumes:
      - ./hadoop-config/core-site.xml:/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop-network

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    environment:
      - HDFS_DATANODE_HOSTNAME=datanode
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - hadoop-network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
    networks:
      - hadoop-network

  nodemanager:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - resourcemanager
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge

volumes:
  namenode_data:
  datanode_data:
