version: '3.8'

services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=test-cluster
    ports:
      - "9870:9870"  # HDFS Web UI
      - "9000:9000"  # HDFS NameNode
    networks:
      - hadoop-net
    volumes:
      - namenode:/hadoop/dfs/name

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    networks:
      - hadoop-net
    depends_on:
      - hadoop-namenode
    volumes:
      - datanode:/hadoop/dfs/data

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master
    networks:
      - hadoop-net

  spark-worker:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - hadoop-net

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"  # Cassandra CQL Port
    networks:
      - hadoop-net
    volumes:
      - cassandra_data:/var/lib/cassandra

networks:
  hadoop-net:

volumes:
  namenode:
  datanode:
  cassandra_data:
