version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop_cluster
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager
    depends_on:
      - resourcemanager

  spark:
    image: bde2020/spark-master:latest
    container_name: spark-master
    ports:
      - "18080:8080"  # Change external port to 18080 since I have other services using 8080
      - "4040:4040"
    depends_on:
      - namenode
      - datanode
      - resourcemanager


  hive-server:
    image: bde2020/hive:latest
    container_name: hive-server
    ports:
      - "10000:10000"
    depends_on:
      - namenode
      - datanode

volumes:
  hadoop_namenode:
  hadoop_datanode:
